### ISSUE TITLE
Add ability to update LICENSE file in root of repository

### ISSUE THREAD

**Issue by klmcadams** [ansys/pre-commit-hooks#117]
### 📝 Description of the feature

Copy the MIT.txt file in the assets folder to the LICENSE file in the root of the repositories if the files are different. 

### 💡 Steps for implementing the feature

Check if the files are different. If they are, shutil.copyfile(assets/LICENSES/MIT.txt, LICENSES) as long as both licenses are MIT

**Comment by RobPasMue** [comment]
Let's give priority to this one whenever you have the chance :) probably after the changelog actions
