### ISSUE TITLE
Recursion limit reached for large repos in add-license-headers

### ISSUE THREAD

**Issue by klmcadams** [ansys/pre-commit-hooks#152]
There is a recursion error due to the high number of files (~5000) that have their headers checked. The solution for this is to remove recursion and use a for loop (for file in files). Figure out if there's a way to make this for loop faster without using recursion

  File "<string>", line 1, in <lambda>
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by RobPasMue** [comment]
Out of curiosity, is it one of our public repos?

**Comment by RobPasMue** [comment]
In any case - I don't expect performance to be highly impacted by changing the logic from recursion to iteration... But we'll see. Nonetheless, it will make the logic much more legible for outsiders. So, it is a positive change in any case.

**Comment by klmcadams** [comment]
> Out of curiosity, is it one of our public repos?

No, it's an internal one

**Comment by klmcadams** [comment]
Closed by #163
