### ISSUE TITLE
Release mechanism through "changelog trigger" not working on ansys/pre-commit-hooks

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pre-commit-hooks#171]
I had to manually build 0.3.1

The current changelog build and release process for this repo will not work out of the box. The problem is that the tag will not be associated to the main branch and consequently, pre-commit won't accept it as an update.

We got numerous pre-commit.ci PRs bumping from 0.3.0 to 0.2.9, and if you run locally ``pre-commit autoupdate`` it also asks you to bump it down. My suggestion is that we either solve this issue so that the tag is not an orphan tag for this repo, or we remove the action altogether for this repo and we build the changelog manually prior to releasing.

**Comment by klmcadams** [comment]
Closed by [ansys/actions #526](https://github.com/ansys/actions/pull/526)
