### ISSUE TITLE
When releasing an orphan tag is created (no history) preventing it to be detected by pre-commit autoupdate

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pre-commit-hooks#203]
Like the title says.

The tag has to be created on the main branch @klmcadams - currently the action is creating the tag on an orphan branch, not on main. The workflow has to be adapted.

**Comment by RobPasMue** [comment]
This is high priority whenever you are back.

**Comment by klmcadams** [comment]
Closed by [ansys/actions #526](https://github.com/ansys/actions/pull/526)
