### ISSUE TITLE
Add default file types to run add-license-headers on

### ISSUE THREAD

**Issue by klmcadams** [ansys/pre-commit-hooks#50]
### 📝 Description of the feature

Determine which files we should have license headers on (*.py, *.cpp, *.yaml, etc.) and add "files" to the .pre-commit-hook.yaml file to make it universal

### 💡 Steps for implementing the feature

1. Determine the types of files we need headers on
2. Add "files" to the hook in .pre-commit-hook.yaml with the correct regex 

### 🔗 Useful links and references

https://[pre-commit](https://pre-commit.com/#hooks-files).com/#hooks-files
https://docs.python.org/3/library/re.html#regular-expression-syntax

**Comment by RobPasMue** [comment]
This requires feedback from @PyJagoda and @MaxJPRey - please sync and let us know which files in a repository should have license headers. At the moment we are only assuming that the source code needs the license header (i.e. all files inside the ``src`` folder)
