### ISSUE TITLE
.reuse/dep5 is ignored if running in a location other than ./

### ISSUE THREAD

**Issue by klmcadams** [ansys/pre-commit-hooks#56]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Wanted to ignore a specific file in the src directory, but it is not being ignored even after being put in dep5. 

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.1.3
  hooks:
  - id: add-license-headers
    args:
    - --loc=src

It seems like the dep5 is only respected if --loc=./, so either find a way to point to the root reuse directory, or copy dep5 to the the folders provided in the loc argument 

### 📝 Steps to reproduce

- Add the hook to your repo
- Specify --loc=src in .pre-commit-config.yaml
- Add a test.py file to src
- Add src/test.py to dep5
- Run the hook 

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

N/A

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
N/A
```

**Comment by RobPasMue** [comment]
I am starting to reconsider the ``loc`` argument.. maybe we should just run the hook from the root of the repository. I'm guessing that'd simplify things a lot.

What do you think @klmcadams?

Pinging also @jorgepiloto and @MaxJPRey

**Comment by klmcadams** [comment]
> I am starting to reconsider the `loc` argument.. maybe we should just run the hook from the root of the repository. I'm guessing that'd simplify things a lot.
> 
> What do you think @klmcadams?
> 
> Pinging also @jorgepiloto and @MaxJPRey

If we take away the loc argument, it will require people using the hook to manually update the dep5 file which could be tedious for them depending on how many specific files they want to ignore. I don't have a problem running the hook from the root of the directory though

**Comment by RobPasMue** [comment]
Well, if their repo is "special" they should also have their own "special" .dep5 file. So... that makes sense.
I think it might be a good solution.
