### ISSUE TITLE
Add an option to add_license_headers so that it considers only the files managed by Git

### ISSUE THREAD

**Issue by ansjhenry** [ansys/pre-commit-hooks#78]
### 📝 Description of the feature

I often have temporary files in my repositories that are not added to Git. The hook add_license_headers complains about those and prevents a commit to be performed.
The workaround consisting of declaring those files or extensions in .reuse/dep5 does not work for me: I wouldn't like to add files/extensions that are not relevant for the project or that couldn't be understood by other contributors.
So, I've to disable this hook until an option is added or this becomes the default behavior.

**Comment by klmcadams** [comment]
@ansjhenry Thanks for your request! I will work on fixing this. What release version of the ansys-pre-commit-hooks repository are you using?

**Comment by ansjhenry** [comment]
@klmcadams My version was 0.1.3. Upgrading to 0.2.0 solves my issue indeed, thanks a lot.
