### ISSUE TITLE
add-license-headers undoes earlier pre-commit hook changes sometimes

### ISSUE THREAD

**Issue by klmcadams** [ansys/pre-commit-hooks#82]
For example, if the .pre-commit-config.yaml file has black as a hook and black modifies a file, add-license-headers may undo its change.
If the file looked like this after black modified it:

```


def func():
```

add-license-headers then adds the header and removes the double newline:

```
# end of license header

def func():
```

When `pre-commit` is run again, it edits the file using black, and then add-license-headers undoes black's changes. This has also happened with docformatter

**Comment by RobPasMue** [comment]
I thought this had been solved in your last PR 😮

**Comment by klmcadams** [comment]
> I thought this had been solved in your last PR 😮

The last PR was just to print out that files had been modified because previously it would say the hook failed with no output of which files were modified. I'll have to see if I can adjust how it's pasting the header into the files to fix this issue

**Comment by RobPasMue** [comment]
Got it - thanks for the explanation!
